# Podfile for Woorijib iOS App

platform :ios, '14.0'
use_frameworks!

# Inhibit all warnings from CocoaPods libraries
inhibit_all_warnings!

target 'Woorijib' do
  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'

  # Networking
  pod 'Alamofire', '~> 5.8'

  # Image Loading
  pod 'Kingfisher', '~> 7.10'

  # Storage
  pod 'RealmSwift', '~> 10.45'

  # Utilities
  pod 'SwiftLint'

  # UI Components
  pod 'Lottie-ios', '~> 4.3'

  target 'WoorijibTests' do
    inherit! :search_paths
    # Testing dependencies
  end

  target 'WoorijibUITests' do
    # UI Testing dependencies
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
